[package]
name = "wasm-chess"
version = "0.1.0"
authors = ["snen <seansullygames@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bojanchess = { path = "../../bojanchess" }
wasm-bindgen = "=0.2.61"
