[package]
name = "wasm-chess"
version = "0.1.0"
authors = ["snen <sullivansean27@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
psychess = { path = "../chess" }
wasm-bindgen = "=0.2.61"
